/**
 * HIK Signer Module
 * Signs assets with C2PA, hashes manifest, pins to IPFS, anchors to blockchain.
 */

import { createHash } from "crypto";
import type { BlockchainConfig } from "./blockchain";
import { registerAsset as anchorToBlockchain } from "./blockchain";
import type { StorageConfig } from "./storage";
import {
  uploadToIPFS,
  uploadToLocalIPFS,
  uploadToMockIPFS,
} from "./storage";

export interface HIKCertificate {
  localPath: string;
  manifestHash: string;
  ipfsUrl: string;
  txHash: string;
}

export interface SignerConfig {
  blockchain: BlockchainConfig;
  storage: StorageConfig;
  useLocalIPFS?: boolean;
  /** Use mock IPFS (no external service) - for testing only */
  useMockIPFS?: boolean;
}

/**
 * Creates a C2PA-compatible manifest structure.
 * In production, this would be generated by @contentauth/c2pa-js.
 */
function createManifest(assetPath: string, options?: { claimGenerator?: string }): object {
  return {
    claim_generator: options?.claimGenerator ?? "HumanIsKind/1.0",
    assertions: [
      {
        label: "c2pa.actions.v1",
        data: {
          actions: [
            {
              action: "c2pa.created",
              when: new Date().toISOString(),
              software_agent: "HumanIsKind-SDK",
            },
          ],
        },
      },
      {
        label: "c2pa.hash.data",
        data: {
          alg: "sha256",
          value: createHash("sha256").update(assetPath).digest("hex"),
        },
      },
    ],
    ingredients: [],
    signature: {
      issuer: "Human Is Kind",
      time: new Date().toISOString(),
    },
    asset_ref: assetPath,
  };
}

/**
 * Hashes manifest JSON with SHA-256.
 * Returns hex string (64 chars) for blockchain anchoring.
 */
export function hashManifest(manifest: object): string {
  const json = JSON.stringify(manifest, Object.keys(manifest).sort());
  return createHash("sha256").update(json).digest("hex");
}

/**
 * Full HIK flow: Sign -> Hash -> Upload to IPFS -> Anchor to blockchain.
 * @param assetPath - Path to the asset file
 * @param config - Blockchain and storage configuration
 * @returns HIK Certificate with all verification data
 */
export async function signAndAnchor(
  assetPath: string,
  config: SignerConfig
): Promise<HIKCertificate> {
  // 1. Create manifest (C2PA-compatible structure)
  const manifest = createManifest(assetPath);

  // 2. Hash the manifest
  const manifestHash = hashManifest(manifest);

  // 3. Upload to IPFS
  const ipfsUrl = config.useMockIPFS
    ? uploadToMockIPFS(manifest, manifestHash)
    : config.useLocalIPFS
      ? await uploadToLocalIPFS(manifest, config.storage)
      : await uploadToIPFS(manifest, config.storage);

  // 4. Anchor hash and URI to blockchain
  const txHash = await anchorToBlockchain(
    config.blockchain,
    manifestHash,
    ipfsUrl
  );

  return {
    localPath: assetPath,
    manifestHash,
    ipfsUrl,
    txHash,
  };
}
